'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');const root=path.resolve(__dirname,'..');let source=fs.readFileSync(path.join(root,'server.js'),'utf8');
source=source.replace("const WebSocket = require('ws');",`const WebSocket={OPEN:1,Server:class DummyServer{constructor(){this.clients=new Set()}on(){}}};`);
source=source.replace(/server\.listen\(PORT,[\s\S]*?\);\s*$/m,`module.exports={rooms,createRoom,addCpu,startGame,playCard,advanceReviewToPick,doPick,submitPickTargets,resolvePairChoice,finishAfterPick,beginNextRound,ensureRoomProgress,playableIds,clearAllProgressTimers};`);
const runtime=path.join(root,'.game_engine_stress_runtime.cjs');fs.writeFileSync(runtime,source);
const original={setTimeout:global.setTimeout,clearTimeout:global.clearTimeout,setInterval:global.setInterval,clearInterval:global.clearInterval};const handle=()=>({unref(){}});global.setTimeout=()=>handle();global.clearTimeout=()=>{};global.setInterval=()=>handle();global.clearInterval=()=>{};let api;try{api=require(runtime);}finally{fs.unlinkSync(runtime);}
function fakeWs(){return{readyState:1,sent:[],send(raw){this.sent.push(JSON.parse(raw));}};}
function createGame(rounds,dealMode,shootLimit,feastPointPerCard,pickProviderRole){const socket=fakeWs();api.createRoom(socket,`Human-${rounds}-${dealMode}-${shootLimit}`,rounds,true,-20,false,false,'mud6',2,'perRound',true,dealMode,shootLimit,feastPointPerCard,pickProviderRole);const room=[...api.rooms.values()].at(-1);for(let i=0;i<3;i++)api.addCpu(room,room.hostId);assert.strictEqual(api.startGame(room,room.hostId),true);return room;}
function cards(room){const a=[];for(const p of room.players)a.push(...p.hand,...p.scorePile,...p.pairs);a.push(...(room.stock||[]));if(room.removedCard)a.push(room.removedCard);return a;}
function integrity(room,label){const ids=cards(room).map(c=>c?.id).filter(Boolean);assert.strictEqual(new Set(ids).size,ids.length,`${label}: duplicate active card id`);}
function drive(rounds,dealMode,shootLimit,seed){const feastPointPerCard=[0,1,2,5][seed%4];const pickProviderRole=seed%2?'weakest':'winner';const room=createGame(rounds,dealMode,shootLimit,feastPointPerCard,pickProviderRole);let steps=0,picks=0,pairs=0,spots=0,roundEnds=0;while(room.phase!=='finished'&&steps++<4000){integrity(room,`step ${steps}`);if(room.phase==='roundEnd'){roundEnds++;assert.strictEqual(room.spotlightEvent,null);api.beginNextRound(room);continue;}assert.strictEqual(room.phase,'playing');if(room.trickReview){const r=room.trickReview;api.advanceReviewToPick(room,r.until,r.winnerPid,r.weakestPid);continue;}const pp=room.pendingPick;if(pp){if(pp.targetSelectionRequired&&!pp.targetSelectionDone){const provider=room.players[pp.pickProviderPid];api.submitPickTargets(room,provider.id,provider.hand.slice(0,pp.targetCount).map(c=>c.id),true);continue;}if(pp.pairChoice&&!pp.result){pairs++;const skip=(seed+steps)%3===0;api.resolvePairChoice(room,room.players[pp.pickerPid].id,skip?null:pp.pairChoice.candidates[0]?.id,skip);continue;}if(!pp.result){picks++;pp.readyAt=0;api.doPick(room,room.players[pp.pickerPid].id,(seed+steps)%Math.max(1,pp.targetCount||1));continue;}if(room.spotlightEvent)spots++;api.finishAfterPick(room,pp.winnerPid);continue;}if(room.current==null){api.ensureRoomProgress(room);continue;}const playable=[...api.playableIds(room,room.current)];if(!playable.length){api.ensureRoomProgress(room);continue;}api.playCard(room,room.players[room.current].id,playable[(seed+steps)%playable.length]);}
assert.ok(steps<4000);assert.strictEqual(room.phase,'finished');assert.strictEqual(room.spotlightEvent,null);assert.ok(room.players.every(p=>p.final&&Number.isFinite(p.final.total)&&p.final.feastPointPerCard===feastPointPerCard));integrity(room,'finished');api.clearAllProgressTimers(room);return{rounds,dealMode,shootLimit,feastPointPerCard,pickProviderRole,steps,picks,pairs,spots,roundEnds,shootCounts:room.players.map(p=>p.shootPigActivatedRounds?.length||0),totals:room.players.map(p=>p.final.total)};}
const runs=[];for(const mode of ['reshuffle','carryOver'])for(const limit of ['unlimited','once'])for(let seed=0;seed<4;seed++)runs.push(drive(3,mode,limit,seed));Object.assign(global,original);console.log(JSON.stringify({result:'passed',runs},null,2));
